# Generated by Django 5.2 on 2025-06-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок блога', max_length=50, verbose_name='Загаловок')),
                ('content', models.TextField(help_text='Введите содержимое блога', verbose_name='Содержимое')),
                ('preview', models.ImageField(help_text='Загрузите изображение блога', upload_to='blog/preview', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, help_text='Отметьте, если пост опубликован', verbose_name='Опубликовано')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Количество раз, когда пост был просмотрен', verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['-created_at'],
            },
        ),
    ]
